In [121]:
import pandas as pd

## Get Data and DF shapes

In [176]:
df_season_drivers_2023 = pd.read_csv('../data/Raw/Formula1_2023season_drivers.csv')
df_grand_prix_2023 = pd.read_csv('../data/Raw/all_grand_prix_laps_2023.csv')
df_qualifying_results_2023 = pd.read_csv('../data/Raw/Formula1_2023season_qualifyingResults.csv')
df_driver_of_the_day_2023 = pd.read_csv('../data/Raw/Formula1_2023season_driverOfTheDayVotes.csv')

print(df_season_drivers_2023.shape)
print(df_qualifying_results_2023.shape)
print(df_grand_prix_2023.shape)
print(df_driver_of_the_day_2023.shape)

(22, 13)
(440, 9)
(24431, 33)
(22, 11)

## Convert Qualifying time to seconds

In [184]:
df_qualifying_results_2023_fl = df_qualifying_results_2023.dropna()
df_qualifying_results_2023_fl = df_qualifying_results_2023_fl.replace("DNF", '0.00')
df_qualifying_results_2023_fl["Q3"] = df_qualifying_results_2023_fl["Q3"].astype(str).str.split(':').apply(lambda x:  0.00 if (len(x)) < 2 else (float(x[0]) * 60) + float(x[1]))
df_qualifying_results_2023_fl["Q1"] = df_qualifying_results_2023_fl["Q1"].str.split(":").apply(lambda x: (float(x[0]) * 60) + float(x[1]))
df_qualifying_results_2023_fl["Q2"] = df_qualifying_results_2023_fl["Q2"].str.split(":").apply(lambda x: (float(x[0]) * 60) + float(x[1]))
df_qualifying_results_2023_fl = df_qualifying_results_2023_fl.dropna()

## Convert

In [186]:
df_season_drivers_2023

,Driver,Abbreviation,No,Team,Country,Podiums,Points,Grands Prix Entered,World Championships,Highest Race Finish,Highest Grid Position,Date of Birth,Place of Birth
0,Max Verstappen,VER,1,Red Bull Racing,Netherlands,98,2586.5,185,3,1(x54),1,30/09/1997,"Hasselt, Belgium"
1,Sergio Perez,PER,11,Red Bull Racing,Mexico,35,1486.0,258,0,1(x6),1,26/01/1990,"Guadalajara, Mexico"
2,Lewis Hamilton,HAM,44,Mercedes,United Kingdom,197,4639.5,332,7,1(x103),1,07/01/1985,"Stevenage, England"
3,Fernando Alonso,ALO,14,Aston Martin,Spain,106,2267.0,380,2,1(x32),1,29/07/1981,"Oviedo, Spain"
4,Charles Leclerc,LEC,16,Ferrari,Monaco,30,1074.0,125,0,1(x5),1,16/10/1997,"Monte Carlo, Monaco"
5,Lando Norris,NOR,4,McLaren,United Kingdom,13,633.0,104,0,2(x7),1,13/11/1999,"Bristol, England"
6,Carlos Sainz,SAI,55,Ferrari,Sapin,18,982.5,185,0,1(x2),1,01/09/1994,"Madrid, Spain"
7,George Russell,RUS,63,Mercedes,United Kingdom,11,469.0,104,0,1(x1),1,15/02/1998,"King's Lynn, England"
8,Oscar Piastri,PIA,81,McLaren,Australia,2,97.0,22,0,2(x1),2,06/04/2001,"Melbourne, Victoria"
9,Lance Stroll,STR,18,Aston Martin,Canada,3,268.0,143,0,3(x3),1,29/10/1998,"Montreal, Canada"
10,Pierre Gasly,GAS,10,Alpine,France,4,394.0,130,0,1(x1),2,07/02/1996,"Rouen, France"
11,Esteban Ocon,OCO,31,Alpine,France,3,422.0,133,0,1(x1),3,17/09/1996,"Evreux, Normandy"
12,Alexander Albon,ALB,23,Williams,Thailand,2,228.0,81,0,3(x2),4,23/03/1996,"London, England"
13,Yuki Tsunoda,TSU,22,AlphaTauri,Japan,0,61.0,66,0,4(x1),6,11/05/2000,"Sagamihara, Japan"
14,Valtteri Bottas,BOT,77,Alfa Romeo,Finland,67,1797.0,222,0,1(x10),1,28/08/1989,"Nastola, Finland"
15,Nico Hulkenberg,HUL,27,Haas F1 Team,Germany,0,530.0,206,0,4(x3),1,19/08/1987,"Emmerich am Rhein, Germany"
16,Daniel Ricciardo,RIC,3,AlphaTauri,Australia,32,1317.0,239,0,1(x8),1,01/07/1989,"Perth, Australia"
17,Guanyu Zhou,ZHO,24,Alfa Romeo,China,0,12.0,44,0,8(x1),5,30/05/1999,"Shanghai, China"
18,Kevin Magnussen,MAG,20,Haas F1 Team,Denmark,1,186.0,164,0,2(x1),4,05/10/1992,"Roskilde, Denmark"
19,Liam Lawson,LAW,40,AlphaTauri,New Zealand,0,2.0,5,0,9(x1),10,11/02/2002,"Hastings, New Zealand"
20,Logan Sargeant,SAR,2,Williams,United States,0,1.0,22,0,10(x1),6,31/12/2000,"Fort Lauderdale, Florida"
21,Nyck De Vries,DEV,21,AlphaTauri,Netherlands,0,2.0,11,0,9(x1),8,06/02/1995,"Uitwellingerga, Netherlands"